### ISSUE TITLE
Camera not working

### ISSUE THREAD

**Issue by maandagdev** [markusfisch/CameraView#1]
Hi,

I followed your steps but when the app is build and running on my phone the camera is not shown. No errors. Am I doing something wrong?

**Comment by markusfisch** [comment]
Do you mean the included demo app? If you just clone the repository and run `make` to build, install and run the demo app, does this work?

If not, on what device and what Android version do you run it?

**Comment by maandagdev** [comment]
I used the gradle method, I am using a one plus 6 running android 8.1.0

**Comment by maandagdev** [comment]
I got it working, I copied the code for the permissions and now it works, I however want to overlay something infront of the preview but the preview keeps going infront, do you have any suggestions how I can get that working?

**Comment by markusfisch** [comment]
Simply put the CameraView and the views you want to overlay in a FrameLayout (or something like that) with the CameraView as the first child:
```xml
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
	android:layout_width="match_parent"
	android:layout_height="match_parent">
	<de.markusfisch.android.cameraview.widget.CameraView
		android:id="@+id/camera_view"
		android:layout_width="match_parent"
		android:layout_height="match_parent"/>
	<!-- put your views here -->
</FrameLayout>
```
Here's a real world example: https://github.com/markusfisch/BinaryEye/blob/master/app/src/main/res/layout/activity_camera.xml

If you want to draw something "on" the camera view, I'd use a [SurfaceView](https://developer.android.com/reference/android/view/SurfaceView) as second child. In that case, also have a look at `cameraView.previewRect` what gives you the rectangle of the camera preview. The camera preview may expand slightly beyond its visible boundaries.

**Comment by maandagdev** [comment]
Ah yeah, I see, thank you, for some reason when I first downloaded the project it did not want to work.

Thanks for the help!
