### ISSUE TITLE
Depricated

### ISSUE THREAD

**Issue by MuhammadAjmal661** [markusfisch/CameraView#4]

**Comment by markusfisch** [comment]
[android.hardware.Camera](https://developer.android.com/reference/android/hardware/Camera.html) is deprecated from API level 21 (Android 5.0).

When something is marked as deprecated, it doesn't mean that you can't use it anymore. It means that it will be removed from _new versions_ at some point in the future.

Right now, there are still 10.7% of all devices with access to Google Play below API level 21:
![image](https://user-images.githubusercontent.com/485246/68653856-ed877980-052c-11ea-9feb-27c0f637896e.png)
Source: https://developer.android.com/about/dashboards

So if you want to build apps for people with old versions of Android, you have to use `android.hardware.Camera`. This library is deliberately still on API level 9 (Android 2.3).

If you want you app to use `Camera2` where it's available, have a look at this library:
https://github.com/pvasa/cameraview-ex

If you want to use the latest camera features on the latest devices, you may want to use the new `CameraX` support library (also available from API level 21):
https://developer.android.com/training/camerax

There, you will finally find a [CameraView](https://developer.android.com/reference/androidx/camera/view/CameraView.html) class as part of the SDK.
